[ui]
# paginate = "never"
pager = "delta"
diff-editor = ":builtin"
diff-formatter = ":git"
show-cryptographic-signatures = true

[user]
name = "Brad Clawsie"
email = "brad@b7j0c.org"

[signing]
behavior = "own"
backend = "gpg"
key = "B1C1F1462CE76E5F2D994FB3D817E42DCCB5AB08"

[templates]
git_push_bookmark = '"bradclawsie/push-" ++ change_id.short()'
