#!/usr/bin/env fish

set branch "master"
if test (count $argv) -eq 1
  set branch $argv[1]
end
echo "pull from $branch"

git pull b7j0c $branch
git pull github $branch
git pull sr.ht $branch
git pull codeberg $branch

