#!/usr/bin/env fish

set branch "master"
if test (count $argv) -eq 1
  set branch $argv[1]
end
echo "push to $branch"

git push b7j0c $branch
git push github $branch
git push sr.ht $branch
git push codeberg $branch

