sudo apt install -y libssl-dev openssl libreadline-dev libreadline8 build-essential pkg-config chicken-bin libchicken-dev libchicken11 ca-certificates sqlite3 libsqlite3-dev
sudo chicken-install linenoise
sudo chicken-install openssl
sudo chicken-install simple-loops
sudo chicken-install simple-exceptions
sudo chicken-install http-client
sudo chicken-install srfi-99
sudo chicken-install crypt
sudo chicken-install uuid
sudo chicken-install crypto-tools
sudo chicken-install aes
sudo chicken-install sha2
sudo chicken-install message-digest-primitive
sudo chicken-install message-digest
sudo chicken-install string-utils
sudo chicken-install test
sudo chicken-install sqlite3
sudo chicken-install sql-null
sudo chicken-install coops
sudo chicken-install regex
sudo chicken-install miscmacros
sudo chicken-install coops-utils
