theme = "brad"

[editor]
shell = ["fish", "-c"]
auto-save = true
gutters = ["diagnostics", "diff"]

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
C-s = ":w"

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
