[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.base", "Dockerfile.dev"]

[[language]]
name = "go"
formatter = { command = "gofumpt" }

[[language]]
name = "perl"
file-types = ["t", "pl", "pm"]
indent = { tab-width = 2, unit = "  " }
