[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.base", "Dockerfile.dev"]

[[language]]
name = "go"
config = { "formatting.gofumpt" = true, "ui.diagnostic.staticcheck" = true }

[[language]]
name = "perl"
file-types = ["t", "pl", "pm"]
