.PHONY: libs
libs:
        sudo apt install -y make libedit2 libedit-dev && \
        raco pkg install --skip-installed --auto libuuid && \
        raco pkg install --skip-installed --auto crypto && \
        raco pkg install --skip-installed --auto review && \
        raco pkg install --skip-installed --auto sha && \
        raco pkg update --all && \
        raco setup

