set shell := ["fish", "-c"]
set dotenv-load

default:
    @just --list

pkgs:
	sudo pacman -S \
	ca-certificates \
	openssl \
	postgresql-libs 

libs:
	zef install --/test cro
	zef install App::Prove6
	zef install DBIish
	zef install Digest
	zef install File::Find
	zef install File::Temp
	zef install HTTP::Easy
	zef install JSON::Fast
	zef install PSGI
	zef install Linenoise
	zef install LWP::Simple
	zef install OpenSSL
	zef install UUID::V4

git:
  zef -v install https://github.com/rawleyfowler/Humming-Bird.git
