PHONY: libs
libs:
	zef update
	zef install --force-install App::Prove6
	zef install --force-install --force-test Readline
	zef install --force-install Gcrypt
	zef install --force-install LibUUID
	zef install --force-install String::CRC32
	zef install --force-install Subsets::Common
	zef install --force-install Crypt::Argon2
	zef install --force-install Net::Postgres
	zef install --force-install Humming-Bird
	zef install --force-install JSON::Tiny
