set shell := ["fish", "-c"]
set dotenv-load

default:
    @just --list

pkgs:
	sudo pacman -S \
	ca-certificates \
	openssl \
	postgresql-libs \
	sqlite \
	libgit2

libs:
	cpanm -n \
	App::perlimports \
	Cpanel::JSON::XS \
	CryptX \
	Crypt::Argon2 \
	Crypt::JWT \
	Crypt::Random \
	Data::Pretty \
	DateTime \
	DBD::Pg \
	DBD::SQLite \
	DBI \
	DBIx::Class \
	Dist::Zilla \
	Dist::Zilla::Plugin::GitHub::Meta \
	Dist::Zilla::Plugin::Git::Contributors \
	Dist::Zilla::Plugin::RewriteVersion \
	Dist::Zilla::PluginBundle::Basic \
	File::Slurp \
	Git::Raw \
	Hash::Ordered \
	HTTP::XSHeaders \
	HTTP::XSCookies \
	IO::All \
	IO::Async \
	IO::Socket::Socks \
	IO::Socket::SSL \
	Kelp \
	Log::Dispatch \
	Log::Dispatchouli \
	List::AllUtils \
	Mojolicious \
	Mojo::Log::JSON \
	Mojo::Pg \
	Mojo::SQLite \
	MooseX::Extended \
	Object::Pad \
	Parallel::Forkmanager \
	Perl::Critic \
	Perl::Critic::TooMuchCode \
	Perl::Critic::StricterSubs \
	Perl::Critic::Community \
	Perl::Critic::Bangs \
	Perl::Tidy \
	Perl::Tidy::Sweetened \
	Pod::Perldoc \
	Ref::Util \
	Scalar::Util \
	strictures \
	Syntax::Keyword::Try \
	Term::ReadLine::Gnu \
	Test::Kwalitee \
	Test2::Harness \
	Test2::Suite \
	UUID \
	URI::XSEscape

