PHONY: pkgs
pkgs:
	sudo pacman -S \
	ca-certificates \
	openssl \
	readline \
	sqlite \
	postgresql-libs \
	libgit2

PHONY: libs
libs:
	cpanm -n \
	App::Ack \
	App::perlimports \
	bareword::filehandles \
	Cpanel::JSON::XS \
	CryptX \
	Crypt::Argon2 \
	Crypt::JWT \
	Data::Dumper \
	DateTime \
	DBD::SQLite \
	DBI \
	Devel::REPL \
	Dist::Zilla \
	Dist::Zilla::Plugin::GitHub::Meta \
	Dist::Zilla::Plugin::Git::Contributors \
	Dist::Zilla::Plugin::RewriteVersion \
	Dist::Zilla::PluginBundle::Basic \
	EV \
	File::Slurp \
	Future \
	Future::AsyncAwait \
	Future::IO \
	Git::Raw \
	indirect \
	IO::Socket::Socks \
	IO::Socket::SSL \
	Lang::Go::Mod \
	List::AllUtils \
	List::SomeUtils \
	List::UtilsBy \
	List::MoreUtils \
	Log::Log4perl \
	Log::Log4perl::Layout::JSON \
	Minion \
	Minion::Backend::SQLite \
	Moo \
	Mojolicious \
	Mojo::Log::JSON \
	Mojo::Pg \
	Mojo::SQLite \
	MooseX::Types::Structured \
	MooseX::Extended \
	multidimensional \
	Net::SSLeay \
	Object::Pad \
	Perl::Critic \
	Perl::Critic::TooMuchCode \
	Perl::Critic::StricterSubs \
	Perl::Critic::Community \
	Perl::Critic::Bangs \
	Perl::LanguageServer \
	Perl::Tidy \
	Perl::Tidy::Sweetened \
	Scalar::Util \
	strictures \
	Struct::Dumb \
	Sub::Info \
	Syntax::Keyword::Try \
	Term::ReadLine::Gnu \
	Test::Kwalitee \
	Test2::Harness \
	Test2::Suite \
	Type::Tiny



